# Generated by Django 5.2.12 on 2026-03-20 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_server', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RangeDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deploying', 'Deploying'), ('running', 'Running'), ('stopped', 'Stopped'), ('deleting', 'Deleting'), ('error', 'Error')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeployedVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('proxmox_vmid', models.IntegerField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='pending', max_length=20)),
                ('node', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vms', to='ranges.rangedeployment')),
            ],
        ),
        migrations.CreateModel(
            name='RangeNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('proxmox_sdn_zone', models.CharField(max_length=255)),
                ('proxmox_sdn_vnet', models.CharField(max_length=255)),
                ('subnet', models.CharField(max_length=255)),
                ('gateway', models.CharField(max_length=255)),
                ('auto_assign_ips', models.BooleanField(default=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='ranges.rangedeployment')),
            ],
        ),
        migrations.CreateModel(
            name='DeployedVMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('cores', models.IntegerField(blank=True, null=True)),
                ('memory', models.IntegerField(blank=True, help_text='Memory in MB', null=True)),
                ('node', models.CharField(blank=True, max_length=255, null=True)),
                ('deployed_vm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='ranges.deployedvm')),
                ('network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ranges.rangenetwork')),
            ],
        ),
        migrations.CreateModel(
            name='RangeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='range_templates', to='ranges.tag')),
            ],
        ),
        migrations.AddField(
            model_name='rangedeployment',
            name='range_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ranges.rangetemplate'),
        ),
        migrations.CreateModel(
            name='RangeTemplateNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. LAN, WAN, DMZ', max_length=255)),
                ('proxmox_sdn_zone', models.CharField(max_length=255)),
                ('proxmox_sdn_vnet', models.CharField(max_length=255)),
                ('subnet', models.CharField(help_text='e.g. 10.10.1.0/24', max_length=255)),
                ('gateway', models.CharField(help_text='e.g. 10.10.1.1', max_length=255)),
                ('auto_assign_ips', models.BooleanField(default=True)),
                ('range_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='ranges.rangetemplate')),
            ],
        ),
        migrations.AddField(
            model_name='rangenetwork',
            name='copied_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ranges.rangetemplatenetwork'),
        ),
        migrations.CreateModel(
            name='VMTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('proxmox_template_id', models.IntegerField(help_text='Proxmox template VMID')),
                ('node', models.CharField(help_text='Proxmox node to deploy on', max_length=255)),
                ('cores', models.IntegerField(default=2)),
                ('memory', models.IntegerField(default=2048, help_text='Memory in MB')),
                ('notes', models.TextField(blank=True, null=True)),
                ('config_script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config_server.script')),
                ('range_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vm_templates', to='ranges.rangetemplate')),
            ],
        ),
        migrations.AddField(
            model_name='deployedvm',
            name='vm_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ranges.vmtemplate'),
        ),
    ]
