# Generated by Django 5.2.12 on 2026-03-31 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('deployment_started', 'Deployment Started'), ('deployment_complete', 'Deployment Complete'), ('deployment_stopped', 'Deployment Stopped'), ('deployment_failed', 'Deployment Failed'), ('vm_checkin', 'VM Checked In'), ('vm_failed', 'VM Failed'), ('user_registered', 'User Registered')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
