# Generated by Django 5.2.12 on 2026-04-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0002_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangedeployment',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rangedeployment',
            name='proxmox_pool',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rangedeployment',
            name='status',
            field=models.CharField(choices=[('undeployed', 'Undeployed'), ('pending', 'Pending'), ('deploying', 'Deploying'), ('running', 'Running'), ('stopped', 'Stopped'), ('fragmented', 'Fragmented'), ('deleting', 'Deleting'), ('error', 'Error'), ('archived', 'Archived')], default='undeployed', max_length=20),
        ),
    ]
