# Generated by Django 5.2.12 on 2026-04-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0003_rangedeployment_is_archived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxmox_vmid_min', models.IntegerField(default=200, help_text='Minimum VMID for training VMs')),
                ('proxmox_vmid_max', models.IntegerField(default=999, help_text='Maximum VMID for training VMs')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
