# Generated by Django 5.2.12 on 2026-04-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0004_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMIDLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VMID lock',
            },
        ),
    ]
