# Generated by Django 5.2.12 on 2026-04-07 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0005_vmidlock'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMTemplateNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_index', models.IntegerField(default=0, help_text='NIC index e.g. 0=net0, 1=net1')),
                ('manual_vnet', models.CharField(blank=True, help_text='Manual vnet if no network selected', max_length=255, null=True)),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ranges.rangetemplatenetwork')),
                ('vm_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_interfaces', to='ranges.vmtemplate')),
            ],
            options={
                'ordering': ['interface_index'],
                'unique_together': {('vm_template', 'interface_index')},
            },
        ),
    ]
