# Generated by Django 5.2.12 on 2026-04-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0006_vmtemplatenetwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmtemplatenetwork',
            name='vlan_tag',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional VLAN tag (1–4094)', null=True),
        ),
    ]
