# Generated by Django 5.2.12 on 2026-04-11 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0007_vmtemplatenetwork_vlan_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployedVMNIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_index', models.IntegerField(help_text='NIC index e.g. 0=net0, 1=net1')),
                ('mac_address', models.CharField(max_length=17)),
                ('deployed_vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nics', to='ranges.deployedvm')),
            ],
            options={
                'ordering': ['interface_index'],
                'unique_together': {('deployed_vm', 'interface_index')},
            },
        ),
    ]
