# Generated by Django 5.2.15 on 2026-06-29 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0008_deployedvmnic'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployedVMVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True, default='')),
                ('deployed_vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='ranges.deployedvm')),
            ],
            options={
                'unique_together': {('deployed_vm', 'key')},
            },
        ),
    ]
