# Generated by Django 5.2.12 on 2026-03-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeployedVMVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MachineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('config_script', models.TextField(help_text='Rendered script served to VM on boot')),
                ('has_checked_in', models.BooleanField(default=False)),
                ('last_checkin', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('script_type', models.CharField(choices=[('bootstrap', 'Bootstrap'), ('config', 'Config'), ('teardown', 'Teardown')], default='config', max_length=20)),
                ('content', models.TextField(help_text='Use {{ variable_name }} for variables')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='e.g. ip_address, hostname', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('variable_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('ip_address', 'IP Address')], default='string', max_length=20)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('required', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='Auto populated from deployment config')),
            ],
        ),
    ]
