# Generated by Django 5.2.12 on 2026-03-20 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_server', '0001_initial'),
        ('ranges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deployedvmvariable',
            name='deployed_vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='ranges.deployedvm'),
        ),
        migrations.AddField(
            model_name='machineconfig',
            name='deployed_vm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='machine_config', to='ranges.deployedvm'),
        ),
        migrations.AddField(
            model_name='script',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='script',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='scripts', to='ranges.tag'),
        ),
        migrations.AddField(
            model_name='scriptvariable',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='config_server.script'),
        ),
        migrations.AddField(
            model_name='deployedvmvariable',
            name='script_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config_server.scriptvariable'),
        ),
        migrations.AlterUniqueTogether(
            name='deployedvmvariable',
            unique_together={('deployed_vm', 'key')},
        ),
    ]
