# Generated by Django 5.2.12 on 2026-04-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_server', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='is_public',
        ),
        migrations.AddField(
            model_name='script',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public_view', 'Public — view only'), ('public_edit', 'Public — editable')], default='private', max_length=20),
        ),
    ]
