# Generated by Django 5.2.15 on 2026-06-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_server', '0003_remove_script_is_public_script_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='script_language',
            field=models.CharField(choices=[('bash', 'Bash'), ('powershell', 'PowerShell'), ('python', 'Python'), ('vyos', 'VyOS'), ('other', 'Other')], default='bash', help_text='Script language/interpreter', max_length=20),
        ),
    ]
