# Generated by Django 5.2.15 on 2026-06-29 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_server', '0004_script_script_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeployedVMVariable',
        ),
    ]
